({
	"loadingState":"Loading...",
	"errorState":"Error occured!",
	"pgnof":"of",
	"pgnRowsPerPage":"Rows/page",
	"pgnGotoPage":"Go to page",
	"pgnPrivious":"Privious",
	"pgnNext":"Next",
	"pgnHitEnter":"Press enter to continue",
	"filter":"Filter",
	"refresh":"Refresh",
	"edit": "Edit",
	"close":"Close",
	"_delete": "Delete",
	"addRow":"Add Row",
	"clearSelection":"Clear Selection",
	"pgnRowsPerPageWarn":"By changing rows per page you will loose selections made earlier on all pages. Press enter to continue.",
	"sortable":"Sortable",
	"contains" : "Contains",
	"does-not-contain" : "Does not contain",
	"starts-with" : "Starts with",
	"ends-with" : "Ends with",
	"empty" : "Empty",
	"not-empty" : "Not empty",
	"equal" : "==",
	"not-equal" : "!=",
	"greater-then" : ">",
	"greater-then-euqal-to" : ">=",
	"less-then" : "<",
	"less-then-equal-to" : "<=",
	"true":"Is equal to",
	"false":"Is not equal to"
})